version: '3.9'

services:
  db:
    image: 'postgres:alpine'
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=biathlon

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    depends_on:
      - db
