version: '3.9'

services:
  db:
    image: 'postgres:alpine'
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=biathlon

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db
      - rabbitmq
