spring:
  liquibase:
    change-log: classpath:db.changelog/db-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/biathlon
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
server:
  port: 9092
simple-socket:
  enabled: false
  port: 9091


grpc:
  server:
    port: 8443
    security:
      private-key: classpath:certs/server.key
      certificate-chain: classpath:certs/server.crt
      enabled: true
    address: 10.242.0.1

#grpc:
#  port: 9092
#  security:
#    cert-chain: classpath:certs/server.crt
#    private-key: classpath:certs/server.key