spring:
  liquibase:
    change-log: classpath:db.changelog/db-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/biathlon
