spring:
  liquibase:
    change-log: classpath:db.changelog/db-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5430/biathlon
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest