spring:
  liquibase:
    change-log: classpath:db.changelog/db-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/biathlon
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
server:
  port: 9090
simple-socket:
  enabled: false
  port: 9091

grpc:
  server:
    port: 9092
    security:
      certificate-chain: certs/server.crt
      private-key: certs/server.key